spring:
  application:
    name: belajar-springboot
  datasource:
    hikari:
      connection-timeout: 20000
      idle-timeout: 10000
      max-lifetime: 600000
      maximum-pool-size: 50
    url: jdbc:postgresql://localhost:5432/belajar_springboot
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_inserts: true
    show-sql: true

server:
  port: 1234

#custom configuration
app:
  currency: IDR
  name: Belajar Spring Boot

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8089
