spring:
  application:
    name: belajar-springboot
server:
  port: 1234

#custom configuration
app:
  currency: IDR
  name: Belajar Spring Boot

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8089
